services:
  web:
    build: .
    container_name: ruby_container
    command: bash -c "rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
    environment:
      - BUNDLE_PATH=/bundle

volumes:
  db: {}
  bundle: {}
  node_modules: {}